/* Automatically generated header (sfdc 1.11)! Do not edit! */

#ifndef CLIB_AMBOSDATA_PROTOS_H
#define CLIB_AMBOSDATA_PROTOS_H

/*
**   $VER: ambosdata_protos.h
**
**   C prototypes. For use with 32 bit integers only.
**
**   Copyright (c) 2001 Amiga, Inc.
**       All Rights Reserved
*/

#include <exec/types.h>
#include <pragmas/AmBoSData_pragmas.h>
#include <utility/tagitem.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* This SFD file was automatically generated by fd2sfd from */
/* ambos/include/FD/AmBoSData.fd and */
/* ambos/include/clib/AmBoSData_protos.h. */
APTR ADataSet(struct TagItem* Tags);
APTR ADataSetTags(Tag Tags, ...);
APTR AGetAttr(APTR Object, struct TagItem* Tags);
APTR AGetAttrTags(APTR Object, Tag Tags, ...);
APTR ASetAttr(APTR Object, struct TagItem* Tags);
APTR ASetAttrTags(APTR Object, Tag Tags, ...);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_AMBOSDATA_PROTOS_H */
